---
title: "Einfache Datenerhebung und -analyse "
output:
  flexdashboard::flex_dashboard:
    storyboard: true
    css: styles.css
    logo: logo.png
    favicon: favicon.png
  pdf_document: default
  word_document: default
---



```{r include=FALSE}

library(knitr)
library(kableExtra)
library(flexdashboard)
library(WDI)
library(tidyverse)
library(plotly)
library(crosstalk)
library(ggthemes)
library(ggplot2)
library(knitr)
library(esquisse)
library(DT)
library(Rcmdr)
library(leaflet)
library(dplyr)
library(ggmap)
library(rgdal)
library(htmltools)
library(mapview)
library(htmlwidgets)
library(maps)
library(leaflet.extras)
library(leaflet)
library(readxl)

```
Karten {.storyboard}
=====================================
### Karte 1


Ein Beispiel



```{r include=FALSE}

#Load counties shape file.
region <- readOGR("sverige4.shp")



bins=c(-500, 0, 1000, 2000, 5000, 15000, 25000)
pal = colorBin(palette = "YlOrBr", region$diff, bins=bins, ".")


region$label <- paste("<p>", region$Län, "</p>",
                           "<p>", "Bevölkerungsdichte:", " ",region$bevdi, " ", "</p>",
                      "<p>", "Bevölkerungswachstum:", " ", region$Differenz, "</p>",
                           sep="")

#add shapefile with the addPolygons function
m <- leaflet(data = region) %>%
  addTiles() %>%
  setView(lng = 12, lat = 63, zoom = 5) %>%
  addPolygons(data = region,
              fillColor = ~pal(diff),
              weight = 1, 
              smoothFactor = 0.5,
              color = "white",
              fillOpacity = 0.8,
              label = lapply(region$label, HTML)) %>%

  addLegend(
        pal=pal,
        values = ~diff,
        position = "bottomright",
        title ="Bevölkerungswachstum")






```

```{r echo=FALSE}
m
```

Grafiken {data-orientation=rows, .storyboard}
=====================================  

### Einfache Grafik  {data-height=200}




```{r echo=FALSE,  fig.width = 4, fig.height = 3}

data_2021 <- read_excel("beispiel_1.xlsx")

data_n <- data_2021

p <- ggplot(data_n) +
  aes(
    x = Bevölkerungsdichte,
    y = Bevölkerungswachstum,
    colour = Region,
    size = Bevölkerung
  ) +
  geom_point(shape = "circle") +
  scale_color_hue(direction = 1) +
  scale_x_continuous(trans = "log10") +
  theme_minimal()

ggplotly(p)

```

### Grafik 2

```{r plotly-crosstalk}

data_n <- data_2021
shared_data <- data_n %>% 
  select(Region, Bevölkerung, Bevölkerungswachstum, Areal, Bevölkerungsdichte, Landesteil) %>% 
  na.omit() %>% 
  mutate(region = stringr::str_replace(Region, "&", "and"),
          Bevölkerung= round(Bevölkerung, 1),
          Areal = round(Areal, 1)) %>% 
  SharedData$new()

p <- shared_data %>% 
  plot_ly(x = ~Bevölkerungsdichte, y = ~Bevölkerungswachstum, color = ~region,
              hoverinfo = "text",
              text = ~paste("Region:", Region,
                            "<br>Bevölkerung:", Bevölkerung,
                            "<br>Bevölkerungsdichte:",Bevölkerungsdichte,
                            "<br>Bevölkerungswachstum:", Bevölkerungswachstum)) %>% 
  group_by(region) %>% 
  add_markers(size = 3) %>%
  layout(xaxis = list(title = "Bevölkerungswachstum"),
         yaxis = list(title = "Einwohner"),
         legend = list(font = list(size = 16)))

# Combining several selectors

bscols(widths = c(3, 9),
       list(
            filter_checkbox(id = "Landesteil", label = "Landesteil",
                    sharedData = shared_data, group = ~Landesteil),
            filter_select(id = "Region", label = "Region",
                    sharedData = shared_data, group = ~Region),
            filter_slider(id = "slider_ap", label = "Areal in km²",
                    sharedData = shared_data, column = ~Areal),
            filter_slider(id = "slider_ap", label = "Bevölkerungsdichte",
                    sharedData = shared_data, column = ~Bevölkerungsdichte),            
            filter_slider(id = "slider_le", label = "Bevölkerungswachstum",
                    sharedData = shared_data, column = ~Bevölkerungswachstum)
      ),
       p)

```

Tabellen {.storyboard}
=====================================
### Tabelle 1

```{r}
data_tabelle2_2021_csv <- read.csv2("regionen2021.csv")

datatable(
  data_tabelle2_2021_csv, 
  filter = 'top', 
  colnames = c("Region (Provinz)", "Bevölkerung", "Bev.-Wachstum 2021", "Areal in km²", "Bev.-Dicht in Enw pro km²", "Landesteil", "Länskod"),
  caption = 'Tabelle 1: Ein einfaches Beispiel',
  extensions = 'Buttons',
    options = list(dom = 'Bftrip',
        burrons = c('copy', 'csv', 'pdf', 'print')
))



```
